AutoIndicators/Models/ProperLinks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutoIndicators.Models
{
    public class ProperLinks
    {
        public int id { get; set; }
        public string ProperName { get; set; }
        public string Definition { get; set; }
        public string Link { get; set; }
        public string CreatorActor { get; set; }
        public DateTime CreationDate { get; set; }
        public int ContextID { get; set; }
        public DateTime LastModified { get; set; }
    }
}

AutoIndicators/Controllers/ProperLinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;

namespace AutoIndicators.Controllers
{
    public class ProperLinksController : Controller
    {
        //
        // GET: /ProperLinks/
        dynamic myModel = new ExpandoObject();
        //
        // GET: /Acronyms/
        public ActionResult Index()
        {

            return View("~/Views/ProperLinks/ProperLinkList.cshtml");
        }

        public bool getDBdata(string pNameString)
        {
            var list = new List<Models.ProperLinks>();
            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                list = dc.Database.SqlQuery<Models.ProperLinks>("SPROCgetletterProperLink @abbreviationString = {0} ", pNameString).ToList<Models.ProperLinks>();
            }
            myModel.list = list;
            return true;
        }

        public ActionResult AddProperLink()
        {
            return View();
        }

        public ActionResult ProperLinkList(string ProperName, string Row)
        {
            getDBdata(ProperName);
            myModel.Row = Row;
            return View(myModel);
        }

        public ActionResult ProperLinkList_noLayout(string ProperName, string Row)
        {
            getDBdata(ProperName);
            myModel.Row = Row;
            return View(myModel);
        }

        public ActionResult EditProperLink(int ID)
        {
            var list = new List<Models.ProperLinks>();
            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                list = dc.Database.SqlQuery<Models.ProperLinks>("SPROCgetSingleProperLink @PID = {0} ", ID).ToList<Models.ProperLinks>();
            }
            myModel.list = list;
            return View(myModel);
        }

        public ActionResult SeeProperLink(int ID)
        {
            var list = new List<Models.ProperLinks>();
            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                list = dc.Database.SqlQuery<Models.ProperLinks>("SPROCgetsingleProperLink @PID = {0} ", ID).ToList<Models.ProperLinks>();
            }
            myModel.list = list;
            return View(myModel);

        }

        public ActionResult Save(FormCollection collection)
        {
            string usr = User.Identity.Name;

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                if (collection["OperationType"] == "1") //Create
                {
                    var parames = new object[] { collection["pProperName"], collection["pDefinition"], collection["pLink"], usr, null };
                    dc.Database.SqlQuery<Models.DefaultWW>(@"SPROCCreateProperLinks @PName= {0}, @PDefinition = {1}, @PLink = {2},@PCreatorActor = {3},@PContextID = {4}", parames).ToList<Models.DefaultWW>();
                }
                else if (collection["OperationType"] == "2") //Update
                {
                    var parames = new object[] { collection["ID"], collection["pProperName"], collection["pDefinition"], collection["pLink"] };
                    dc.Database.SqlQuery<Models.DefaultWW>(@"SPROCUpdateProperLink @PID={0},@PProperName = {1},@PDefinition = {2}, @PLink = {3}", parames).ToList<Models.DefaultWW>();
                }
            }
            return RedirectToAction("Index");
        }
	}
}

AutoIndicators/Views/ProperLinks/AddProperLink.cshtml
@using AutoIndicators.Models
@model dynamic
@{
    Layout = null;
}
@using (Html.BeginForm("Save", "ProperLinks", FormMethod.Post, new { onsubmit = "return validateForm()", id = "CommentForm" }))
{
    @*@Html.Hidden("AcronymID", (int)Model.AcronymID)*@
    @Html.Hidden("OperationType", "1");


    <table width="400" align="center" id="SnapshotTable" class="SnapShot">
        <colgroup>
            <col span="1" style="width: 30%;">
            <col span="1" style="width: 70%;">
        </colgroup>
        <tbody>
            <tr>
                <td>@Html.Label("Proper Name:")</td>
                <td>
                    @Html.TextBox("pProperName", null, new { required = string.Empty })
                </td>
            </tr>
            <tr>
                <td>@Html.Label("Definition: ")</td>
                <td>
                    @Html.TextArea("pDefinition", null, new { required = string.Empty })
                </td>
            </tr>
            <tr>
                <td>@Html.Label("Link: ")</td>
                <td>
                    @Html.TextBox("pLink", null, new {required = string.Empty })
                </td>
            </tr>
            <tr>
                <td></td>
                <td align="right"><input type="submit" value="Save" id="saveBtn" /></td>
            </tr>
        </tbody>
    </table>

}

@section Scripts
{
    <link href="@Url.Content("~/Content/commentStyle.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        // WHEN CLOSE CLICK HIDE THE ERROR / WARNING .
        $('body').on('click', '.close', function (e) {
            $("#warning").hide();
        });
    </script>

    <script type="text/javascript">
        $('#CommentForm').submit(function () {
            $(this).find('input[type=submit]').attr('disabled', 'disabled');
        });
    </script>
}

AutoIndicators/Views/ProperLinks/EditProperLink.cshtml
@using AutoIndicators.Models
@model dynamic
@{
    Layout = null;
}
@using (Html.BeginForm("Save", "ProperLinks", FormMethod.Post, new { onsubmit = "return validateForm()", id = "CommentForm" }))
{

    @Html.Hidden("OperationType", "2");
    foreach (var item in Model.list)
    {
    @Html.Hidden("ID", (int)@item.id);
    <table width="400" align="center" id="SnapshotTable" class="SnapShot">
        <colgroup>
            <col span="1" style="width: 30%;">
            <col span="1" style="width: 70%;">
        </colgroup>
        <tbody>
            <tr>
                <td>@Html.Label("Proper Name:")</td>
                <td>
                    @Html.TextBox("pProperName", (string)@item.ProperName, new { required = string.Empty })
                </td>
            </tr>
            <tr>
                <td>@Html.Label("Definition: ")</td>
                <td>
                    @Html.TextArea("pDefinition", (string)@item.Definition, new { required = string.Empty })
                </td>
            </tr>
            <tr>
                <td>@Html.Label("Link: ")</td>
                <td>
                    @Html.TextBox("pLink", (string)@item.Link, new { required = string.Empty })
                </td>
            </tr>
            <tr>
                <td></td>
                <td align="right"><input type="submit" value="Save" id="saveBtn" /></td>
            </tr>
        </tbody>
    </table>
  }
}

@section Scripts
{
    <link href="@Url.Content("~/Content/commentStyle.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        // WHEN CLOSE CLICK HIDE THE ERROR / WARNING .
        $('body').on('click', '.close', function (e) {
            $("#warning").hide();
        });
    </script>

    <script type="text/javascript">
        $('#CommentForm').submit(function () {
            $(this).find('input[type=submit]').attr('disabled', 'disabled');
        });
    </script>
}

AutoIndicators/Views/ProperLinks/ProperLinkList.cshtml
@using AutoIndicators.Models
@model dynamic
<link href="@Url.Content("~/Content/AcronymStyle.css")" rel="stylesheet" type="text/css" />

@*Modal for the Pop-Up View*@
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Program Add</h4>
            </div>
            <div class="modal-body" id="modalContainer">
                ...
            </div>
        </div>
    </div>
</div>

<div id="tableSearcher">
    <div id="SearchBox">
        <div>
            <a onclick="showPopUp(null); return false;" href="fallback.html">Add a new Proper Link</a>

        </div>
    </div>


    <div id="algo">
    </div>
    <div id="letterChooser">
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "A" })'> A </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "B" })'> B </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "C" })'> C </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "D" })'> D </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "E" })'> E </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "F" })'> F </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "G" })'> G </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "H" })'> H </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "I" })'> I </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "J" })'> J </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "K" })'> K </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "L" })'> L </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "M" })'> M </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "N" })'> N </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "O" })'> O </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "P" })'> P </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "Q" })'> Q </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "R" })'> R </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "S" })'> S </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "T" })'> T </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "U" })'> U </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "V" })'> V </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "W" })'> W </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "X" })'> X </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "Y" })'> Y </a>
        <a href='@Url.Action("ProperLinkList", "ProperLinks", new { ProperName = "Z" })'> Z </a>
    </div>

    <div id="dynamicTable">
        @using (Html.BeginForm())
        {
            if (Model != null)
            {
                <table width="100%" align="center" id="acronymTable" class="table table-bordered table-striped">
                    <thead id="TableHeaders">
                        <tr>
                            <th id="hProperName" align="center" height="30">Proper Name</th>
                            <th id="hDefinition" align="center">Definition</th>
                            <th id="hLink" align="center">Link</th>
                        </tr>
                    </thead>
                    @{int i = 0;}
                    @foreach (var item in Model.list)
                    {
                        i++;
                        <tr id="@item.id">
                            <td id="@("CProperName_" + i.ToString())"><a onclick="showPopUp(@item.id); return false;" href="fallback.html">@item.ProperName</a></td>
                            <td id="@("CDefinition_" + i.ToString())"> @item.Definition</td>
                            <td id="@("CLink_" + i.ToString())"> @item.Link</td>
                        </tr>
                    }


                </table>
            }

        }
    </div>

</div>

<script type="text/javascript">
    //Function to show the popup and pass the correct PWID to the view
    function showPopUp(ID) {
        if (ID == null) {
            var urlLink = "/ProperLinks/AddProperLink";
            $('#myModalLabel').html("Add a Proper Link")
            $('#Modal').data('url', urlLink);

            var url = $('#Modal').data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#Modal').modal("show");

            });
        }
        else {
            var textScheduleID = ID.toString();
            var text = "/ProperLinks/EditProperLink?ID=";
            var urlLink = text + textScheduleID;
            $('#myModalLabel').html("Edit the Proper Link")
            $('#Modal').data('url', urlLink);

            var url = $('#Modal').data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#Modal').modal("show");

            });
        }


    }
</script>

AutoIndicators/Views/ProperLinks/ProperLinkList_noLayout.cshtml
@using AutoIndicators.Models
@model dynamic
<link href="@Url.Content("~/Content/AcronymStyle.css")" rel="stylesheet" type="text/css" />
@{
    Layout = null;
}

@*Modal for the Pop-Up View*@
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Program Add</h4>
            </div>
            <div class="modal-body" id="modalContainer">
                ...
            </div>
        </div>
    </div>
</div>

<div id="tableSearcher">
    <div id="SearchBox">
        <div>
            <a onclick="showPopUp(null); return false;" href="fallback.html">Add a new Proper Link</a>

        </div>
    </div>


    <div id="algo">
    </div>
    <div id="letterChooser">
        <a onclick="showPopUpProperLink('A', 1); return false;" href="fallback.html">A</a>
        <a onclick="showPopUpProperLink('B', 1); return false;" href="fallback.html">B</a>
        <a onclick="showPopUpProperLink('C', 1); return false;" href="fallback.html">C</a>
        <a onclick="showPopUpProperLink('D', 1); return false;" href="fallback.html">D</a>
        <a onclick="showPopUpProperLink('E', 1); return false;" href="fallback.html">E</a>
        <a onclick="showPopUpProperLink('F', 1); return false;" href="fallback.html">F</a>
        <a onclick="showPopUpProperLink('G', 1); return false;" href="fallback.html">G</a>
        <a onclick="showPopUpProperLink('H', 1); return false;" href="fallback.html">H</a>
        <a onclick="showPopUpProperLink('I', 1); return false;" href="fallback.html">I</a>
        <a onclick="showPopUpProperLink('J', 1); return false;" href="fallback.html">J</a>
        <a onclick="showPopUpProperLink('K', 1); return false;" href="fallback.html">K</a>
        <a onclick="showPopUpProperLink('L', 1); return false;" href="fallback.html">L</a>
        <a onclick="showPopUpProperLink('M', 1); return false;" href="fallback.html">M</a>
        <a onclick="showPopUpProperLink('N', 1); return false;" href="fallback.html">N</a>
        <a onclick="showPopUpProperLink('O', 1); return false;" href="fallback.html">O</a>
        <a onclick="showPopUpProperLink('P', 1); return false;" href="fallback.html">P</a>
        <a onclick="showPopUpProperLink('Q', 1); return false;" href="fallback.html">Q</a>
        <a onclick="showPopUpProperLink('R', 1); return false;" href="fallback.html">R</a>
        <a onclick="showPopUpProperLink('S', 1); return false;" href="fallback.html">S</a>
        <a onclick="showPopUpProperLink('T', 1); return false;" href="fallback.html">T</a>
        <a onclick="showPopUpProperLink('U', 1); return false;" href="fallback.html">U</a>
        <a onclick="showPopUpProperLink('V', 1); return false;" href="fallback.html">V</a>
        <a onclick="showPopUpProperLink('W', 1); return false;" href="fallback.html">W</a>
        <a onclick="showPopUpProperLink('X', 1); return false;" href="fallback.html">X</a>
        <a onclick="showPopUpProperLink('Y', 1); return false;" href="fallback.html">Y</a>
        <a onclick="showPopUpProperLink('Z', 1); return false;" href="fallback.html">Z</a>

    </div>

    <div id="dynamicTable">
        @using (Html.BeginForm())
        {
            if (Model != null)
            {
                <table width="100%" align="center" id="acronymTable" class="table table-bordered table-striped">
                    <thead id="TableHeaders">
                        <tr>
                            <th id="hProperName" align="center" height="30">Proper Name</th>
                            <th id="hDefinition" align="center">Definition</th>
                            <th id="hLink" align="center">Link</th>
                            <th id="hAdd" align="center">Add Proper Link</th>
                        </tr>
                    </thead>
                    @{int i = 0;}
                    @foreach (var item in Model.list)
                    {
                        i++;
                        <tr id="@item.id">
                            <td id="@("CProperName_" + i.ToString())"><a onclick="showPopUp(@item.id); return false;" href="fallback.html">@item.ProperName</a></td>
                            <td id="@("CDefinition_" + i.ToString())"> @item.Definition</td>
                            <td id="@("CLink_" + i.ToString())"> @item.Link</td>
                            <td id="@("CLink"+i.ToString())"><a onclick="UpdateProperLink('@item.ProperName','@item.id','@item.Definition','@item.Link'); return false;" href="fallback.html">Add</a></td>
                        </tr>
                    }


                </table>
            }

        }
    </div>

</div>

<script type="text/javascript">
    //Function to show the popup and pass the correct PWID to the view
    function showPopUpProperLink(ID, num) {

        if (num == 0) {
            var urlLink = "/ProperLink/AddProperLink";
            $('#myModalLabel').html("Add a Proper Link")
            $('#Modal').data('url', urlLink);

            var url = $('#Modal').data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#Modal').modal("show");
            });
        }
        else if (num == 1) {

            var urlLink = "/ProperLinks/ProperLinkList_noLayout?ProperName=" + ID.toString() + "&Row=" + @Model.Row;
            $('#myModalLabel').html("Select an Acronym to add to your comment")
            $('#Modal').data('url', urlLink);

            var url = $('#Modal').data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#Modal').modal("show");
            });

            }
        else {

            var textScheduleID = ID.toString();
            var text = "/Acronyms/EditAcronym?ID=";
            var urlLink = text + textScheduleID;
            $('#myModalLabel').html("Edit the Acronym")
            $('#Modal').data('url', urlLink);

            var url = $('#Modal').data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#Modal').modal("show");

            });
        }
    }
</script>

<script type="text/javascript">
    //Function to Paste back to the comment Section
    function UpdateProperLink(ProperName, ID, Definition, Link) {
        //Construct the link to insert to the <a> tag
        var totalAbbreviation;
        totalAbbreviation = "<a href='" + Link + "'" + "title='" + Definition + "''>" + ProperName + "</a>"
        tinyMCE.get('txtDescription_'+@Model.Row).setContent(tinyMCE.activeEditor.getContent() + totalAbbreviation);
        $('#Modal').modal('hide');
    }
</script>