AutoIndicators/Models/Report.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutoIndicators.Models
{
    public class Report
    {
        public string PWContinuityID { get; set; }
        public string Name { get; set; }
        public string Program { get; set; }
        public string Email { get; set; }
        public int Type { get; set; }
        public string TypeName { get; set; }
        public int SubTypeId { get; set; }
        public string Subtype { get; set; }
        public int Reference { get; set; }
        public int WWID { get; set; }
        public string weekName { get; set; }
        public string Notif { get; set; }
        public int NotifId { get; set; }
        public string IconApp { get; set; }
        public int Owner { get; set; }
        public string OwnerEmail { get; set; }
        public int PT { get; set; }
        public int PXT { get; set; }
        public string Status { get; set; }
        public DateTime CreateDate { get; set; }
        public int Total { get; set; }
    }
    public class NotifReport:Report
    {
        public int Days { get; set; }
        public string Item { get; set; }
        public string AppName { get; set; }
        public int AppId { get; set; }
    }
    public class HIReport:Report
    {
        public int Days { get; set; }
        public string Indicator { get; set; }
    }
    public class ScheduleReport:Report
    {
        public string Milestone { get; set; }
        public string ScheduleType { get; set; }
    }
    public class ReportSanpshotChart
    {
        public int OwnerId { get; set; }
        public string Name { get; set; }
        public string Program { get; set; }
        public string weekName { get; set; }
        public bool Complete { get; set; }
    }
}

AutoIndicators/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoIndicators.Controllers
{
    public class ReportsController : Controller
    {
        dynamic myModel;
        //
        // GET: /Report/
        public ActionResult Index()
        {
            int? WWID=null;
            if (Session["FilWW"] != null && Convert.ToInt32(Session["FilWW"].ToString()) > 0)
                WWID = Convert.ToInt32(Session["FilWW"].ToString());
            
            List<Models.DefaultWW> result = new List<Models.DefaultWW>();

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                if (WWID == null)
                {
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetWorkingWWID").ToList<Models.DefaultWW>();
                }
                else
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").Where(x => x.WWID == WWID).ToList<Models.DefaultWW>();

                WWID = result[0].WWID;
            }

            ViewBag.WWID = WWID;
            ViewBag.WW = result[0].weekName;
            ViewBag.Complete=false;
            return View("ReportsView");
        }
        public ActionResult Users(int Report)
        {
            int? WWID = null;
            if (Session["FilWW"] != null && Convert.ToInt32(Session["FilWW"].ToString()) > 0)
                WWID = Convert.ToInt32(Session["FilWW"].ToString());

            List<Models.DefaultWW> result = new List<Models.DefaultWW>();

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                if (WWID == null)
                {
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetWorkingWWID").ToList<Models.DefaultWW>();
                }
                else
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").Where(x => x.WWID == WWID).ToList<Models.DefaultWW>();

                WWID = result[0].WWID;

                myModel = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").ToList<Models.DefaultWW>();
            }

            ViewBag.WWID = WWID;
            ViewBag.WW = result[0].weekName;
            ViewBag.Complete = false;
            ViewBag.Report = Report;
            return View("ByUsersView",myModel);
        }
        public ActionResult Chart(int Owner, int Report, int Type, int WWIDS,int WWIDE, List<Models.HIReport> DataHI = null, List<Models.ScheduleReport> DataSchedule = null,string Prog="")
        {
            List<Models.DefaultWW> wws = new List<Models.DefaultWW>();

            switch (Report)
            {
                case 1:
                    List<Models.ReportSanpshotChart> data = new List<Models.ReportSanpshotChart>();
                    using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
                    {
                        data = dc.Database.SqlQuery<Models.ReportSanpshotChart>("SPROCgetReportByUserChart @intReport={0}, @intType={1}, @WWIDS={2}, @WWIDE={3}"
                            , new object[] { Report, Type, WWIDS,WWIDE }).ToList<Models.ReportSanpshotChart>();
                    }
                    myModel = data.Where(x => x.OwnerId == Owner).ToList();
                    break;
                case 2:
                    if (DataHI == null)
                        return new EmptyResult();
                    myModel = DataHI.Where(x=> x.WWID>= WWIDS && x.WWID<=WWIDE).ToList<Models.HIReport>();
                    break;
                case 3:
                    if (DataSchedule == null)
                        return new EmptyResult();
                    myModel = DataSchedule.Where(x => x.WWID >= WWIDS && x.WWID <= WWIDE).ToList<Models.ScheduleReport>();
                    break;
                case 7:
                    List<Models.ReportSanpshotChart> report = new List<Models.ReportSanpshotChart>();
                    using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
                    {
                        myModel = dc.Database.SqlQuery<Models.ReportSanpshotChart>("SPROCgetReportByUserChart @intReport={0}, @intType={1}, @WWIDS={2}, @WWIDE={3}, @Program={4}"
                            , new object[] { 1, Type, WWIDS,WWIDE,Prog }).ToList<Models.ReportSanpshotChart>();
                    }
                    break;
            }

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
               wws= dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").ToList<Models.DefaultWW>();
            }
            ViewBag.WWS = wws.Where(x => x.WWID == WWIDS).SingleOrDefault().weekName;
            ViewBag.WWE = wws.Where(x => x.WWID == WWIDE).SingleOrDefault().weekName;
            ViewBag.Report = Report;
            ViewBag.Complete = false;

            return PartialView("UserChartView",myModel);
        }
        public ActionResult Consolidate(bool owner=false, int year=0)
        {
            List<Models.NotifReport> rptReport = new List<Models.NotifReport>();

            int? WWID = null;
            if (Session["FilWW"] != null && Convert.ToInt32(Session["FilWW"].ToString()) > 0)
                WWID = Convert.ToInt32(Session["FilWW"].ToString());

            List<Models.DefaultWW> result = new List<Models.DefaultWW>();

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                ViewBag.validUsers = dc.Database.SqlQuery<Models.Users>("[SPROCgetUsers]").ToList<Models.Users>();
                if (WWID == null)
                {
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetWorkingWWID").ToList<Models.DefaultWW>();
                }
                else
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").Where(x => x.WWID == WWID).ToList<Models.DefaultWW>();

                WWID = result[0].WWID;

                rptReport = dc.Database.SqlQuery<Models.NotifReport>("SPROCgetReports @intWWID={0},@intYear={1}, @intType={2}", new object[] { WWID,year, 6 }).ToList<Models.NotifReport>();
            }

            if(year>0)
            {
                rptReport = rptReport.Where(x => x.CreateDate.Year == year).ToList();
            }

            ViewBag.ByOwner = owner;
            ViewBag.WWID = WWID;
            ViewBag.WW = result[0].weekName;
            ViewBag.Complete = false;
            ViewBag.ByYear = year;
            ViewBag.Archived = result[0].weekstatus == 2 ? true : false;
            return View("ConsolidateView",rptReport);
        }
        public ActionResult Delinquent(bool owner = false)
        {
            List<Models.NotifReport> rptReport = new List<Models.NotifReport>();

            int? WWID = null;
            if (Session["FilWW"] != null && Convert.ToInt32(Session["FilWW"].ToString()) > 0)
                WWID = Convert.ToInt32(Session["FilWW"].ToString());

            List<Models.DefaultWW> result = new List<Models.DefaultWW>();

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                ViewBag.validUsers = dc.Database.SqlQuery<Models.Users>("[SPROCgetUsers]").ToList<Models.Users>();
                if (WWID == null)
                {
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetWorkingWWID").ToList<Models.DefaultWW>();
                }
                else
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetCurrentWWID").Where(x => x.WWID == WWID).ToList<Models.DefaultWW>();

                WWID = result[0].WWID;

                rptReport = dc.Database.SqlQuery<Models.NotifReport>("SPROCgetReports @intWWID={0}, @intType={1}", new object[] { WWID, 6 }).ToList<Models.NotifReport>();

            }

            ViewBag.ByOwner = owner;
            ViewBag.WWID = WWID;
            ViewBag.WW = result[0].weekName;
            ViewBag.Archived = result[0].weekstatus == 2 ? true : false;
            ViewBag.Complete = false;
            
            return View("DelinquentView", rptReport);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NotifyDelinquent(int WWID,string WWName,string Data,string To)
        {
            NotifController notif = new NotifController();
            Models.NotifAssignees Assignee=new Models.NotifAssignees();
            List<Models.NotifAssignees> lstAssign=new List<Models.NotifAssignees>();

            Assignee.Email=To;

            lstAssign.Add(Assignee);

            Assignee = new Models.NotifAssignees();

            Assignee.Email = GeneralClasses.General.FindEmailByAccount(User.Identity.Name);
            lstAssign.Add(Assignee);

            string strBody="";
            string strTitle="";

            strTitle=WWName.Replace("-","'") + " Delinquent in "+Data;
            strBody=Data.Replace(",","<br>");

            notif.SendEmail(WWID, WWName, strBody, lstAssign, strTitle);

            return Json(true);
        }
        public ActionResult Notifweek(int year,bool byYear=false)
        {
            List<Models.NotifReport> rptReport = new List<Models.NotifReport>();

            int? WWID = null;
            if (Session["FilWW"] != null && Convert.ToInt32(Session["FilWW"].ToString()) > 0)
                WWID = Convert.ToInt32(Session["FilWW"].ToString());

            List<Models.DefaultWW> result = new List<Models.DefaultWW>();

            using (Models.DevSQLUserEntities dc = new Models.DevSQLUserEntities())
            {
                ViewBag.validUsers = dc.Database.SqlQuery<Models.Users>("[SPROCgetUsers]").ToList<Models.Users>();
                if (WWID == null)
                {
                    result = dc.Database.SqlQuery<Models.DefaultWW>("SPROCgetWorkingWWID").ToList<Models.DefaultWW>();
                }

AutoIndicators/Views/Reports/DelinquentView.cshtml
@using AutoIndicators.Models
@model List<NotifReport>
@section Scripts
{
    <script>
        module = '@ViewBag.Module';
        view=14;
        skip = '../';
        wwid=@ViewBag.WWID;
       

    </script>
}
@{
    List<int> Delincuents = new List<int>();
    Delincuents.Add(2);
    Delincuents.Add(3);
    Delincuents.Add(4);
    Delincuents.Add(5);
    Delincuents.Add(7);
    bool bArchived = (bool)ViewBag.Archived;
    ViewBag.HiddenFilter = false;
    ViewBag.ShowExtra = true;
    ViewBag.Params = "owner," + ViewBag.ByOwner;
    ViewBag.Module = "Reports/Delinquent";
}
@section Extras{
    @{
       // @GeneralHelpers.MenuExtras(ViewBag.WWID, bArchived, ViewBag.validUsers)
    }
}
<script>
    var mEmail={
        email:''
           ,app:''
           ,create: function (config) {
               var newObject = Object.create(this);
               //If a config object has been used to initialize the
               //sprite, assign those values to the new object
               if (config !== undefined) {
                   Object.keys(config).forEach(function (key) {
                       newObject[key] = config[key];
                   });
               }
               return newObject;
           }
    }

    var Email=mEmail.create();
    var Emails=[];
</script>
<br />
<table align="left" style="background-color:#0062a8; width:100%; text-align:center">
    <tr>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Notifweek", "Reports")">Notification this week</a></td>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Consolidate", "Reports", new { year = DateTime.Now.Year })">Notification Annual by program</a></td>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Consolidate", "Reports",new { owner=true, year=DateTime.Now.Year })">Notification Annual by owner</a></td>
        @if ((bool)ViewBag.ByOwner)
        {
            <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Delinquent", "Reports")">Delinquent this week by program</a></td>
            <td style="border:2px solid white; background-color:white"><a style="color:#0062a8 !important;" href="@Url.Action("Delinquent", "Reports", new { owner = true })">Delinquent this week by owner</a></td>
        }
        else
        {
            <td style="border:2px solid white; background-color:white"><a style="color:#0062a8 !important;" href="@Url.Action("Delinquent", "Reports")">Delinquent this week by program</a></td>
            <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Delinquent", "Reports", new { owner = true })">Delinquent this week by owner</a></td>
        }
    </tr>
</table>
<br />
<br />
<div style="width:100%; text-align: center">
    @if ((bool)ViewBag.ByOwner)
    {
        <h3>Delinquent this week By Owner</h3>
    }
    else
    {
        <h3>Delinquent this week By Program</h3>
    }
</div>
<br /><br />
@if (!(bool)ViewBag.ByOwner)
{
    foreach (var notif in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId)).Select(x => new { x.Program, x.AppName, x.Email }).ToList().Distinct().OrderBy(x => x.Program))
    {
        string strApp = "";
        foreach (string Apps in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId) && x.Program == notif.Program).Select(x => x.AppName).Distinct())
        {
            strApp += "," + Apps;
        }
        if (strApp.Length > 1)
        {
            strApp = strApp.Substring(1);
        }
        <script>
            Email.email='@notif.Email';
            Email.app='@strApp';

            if(Emails.indexOf(Email)<0)
            {
                Emails[Email.length]=Email;
            }
        </script>
    }
}
else
{
    foreach (var notif in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId)).Select(x => new { x.Name, x.AppName, x.Email }).ToList().Distinct().OrderBy(x => x.Name))
    {
        string strApp = "";
        foreach (string Apps in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId) && x.Name == notif.Name).Select(x => x.AppName).Distinct())
        {
            strApp += "," + Apps;
        }

        if (strApp.Length > 1)
        {
            strApp = strApp.Substring(1);
        }
        <script>
            var Email=mEmail.create();
            Email.email='@notif.Email';
            Email.app='@strApp';

            if(Emails.indexOf(Email)<0)
            {
                Emails[Emails.length]=Email;
            }
        </script>
    }
}

<table id="ReporData" style="display:none">
    @if (!(bool)ViewBag.ByOwner) { 
        <tr>
            <th>Program</th>
            <th>Owner</th>
            <th>App</th>
            <th></th>
        </tr>
        foreach (var notif in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId)).Select(x => new { x.Program,x.AppName,x.Email,x.Name }).ToList().Distinct().OrderBy(x=> x.Program))
        {
            string strApp = "";
            foreach(string Apps in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId) && x.Program==notif.Program).Select(x=> x.AppName).Distinct())
            {
                strApp += ","+Apps;
            }
            if (strApp.Length > 1)
            {
                strApp = strApp.Substring(1);
            }
                <tr>
                    <td>@notif.Program</td>
                    <td>@notif.Name</td>
                    <td>@notif.AppName</td>
                    <td><button onclick="Notify('@notif.Email','@strApp')">Email</button></td>
                </tr>
        }
    }
    else
    {
        <tr>
            <th>Owner</th>
            <th>App</th>
            <th>Program</th>
            <th>Notify by</th>
        </tr>
        foreach (var notif in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId)).Select(x => new { x.Name, x.AppName,x.Email,x.Program }).ToList().Distinct().OrderBy(x=> x.Name))
        {
            string strApp = "";
            foreach (string Apps in Model.Where(x => Delincuents.Exists(y => y == x.SubTypeId) && x.Name == notif.Name).Select(x => x.AppName).Distinct())
            {
                strApp += "," + Apps;
            }

            if (strApp.Length > 1)
            {
                strApp = strApp.Substring(1);
            }
            <tr>
                <td>@notif.Name</td>
                <td>@notif.AppName</td>
                <td>@notif.Program</td>
                <td><button onclick="Notify('@notif.Email','@strApp')">Email</button></td>
            </tr>
        }
    }
</table>
<div>
    <div style="width:30%; float:left; height:30px;"></div>
    <div id="dgReport" style="float:left"></div>
</div>
<script>

    var EmailsSent=[];
    changeToGridDelinquentReport();
    function changeToGridDelinquentReport() {
        var tbl = $('#ReporData');
        var type = $('#ReporData').data("type");
        var obj = $.paramquery.tableToArray(tbl);

        var newObj = {
            width: 800,
            height: 600,
            hwrap: false,
            wrap: false,
            title: "Results",
            //DataGrid Menu
            editable: false,
            collapsible: true,
            rowBorders: true,
            filterModel: { mode: 'AND', header: true, on: true },
            datatype: 'local',
            selectionModel: {
                //type: 'cell'
                type: 'cell'
            },
            numberCell: { width: 50, resizable: true },
            hoverMode: 'row',
            scrollModel: { autoFit: false },
            toolbar: {
                items: [{
                    type: 'button', label: 'Send All Emails', listeners: [{
                        click: function () {
                            SendAll();
                        }
                    }]
                }]}
        };

        newObj.dataModel = {
            data: obj.data,
            sorting: "local",
            sortDir: ["up", "down", "up"]
        };
        newObj.colModel = obj.colModel;

        for (i = 0; i < newObj.colModel.length; i++) {
            newObj.colModel[i].width = "150";
        }



        var items = newObj.dataModel.data;
        var result = [];

        for (x = 0; x < newObj.colModel.length; x++) {
            Val = [];
            for (var item, i = 0; item = items[i++];) {
                if (Val.indexOf(item[x]) < 0) {
                    Val[Val.length] = item[x];
                }
            }
            result[result.length] = Val;
        }
        for (i = 0; i < newObj.colModel.length; i++) {
            newObj.colModel[i].filter = {
                type: 'select',
                attr: "multiple",
                cache: null,
                options: result[i],
                condition: 'range',
                listeners: ['change'],
                init: function () {
                    $(this).pqSelect({ checkbox: true, radio: true, width: '100%' });
                }
            };
        }

        newObj.pageModel = { rPP: 1000, type: "local" };

        $grid = $('#dgReport').pqGrid(newObj);


        try {
            if ($('#dgReport').pqGrid() != null)
                $('#dgReport').pqGrid("destroy");

            $grid = $('#dgReport').pqGrid(newObj);

            $($($('#dgReport').children()[0]).children()[1]).click();
            $($($('#dgReport').children()[0]).children()[1]).click();

        } catch (err) { }
    }
    function Notify(email,data)
    {
        @*$.post("/Reports/NotifyDelinquent",{WWID: wwid, WWName: '@ViewBag.WW.Replace("'","-")', Data: data, To:email},function(res){
            if(res)
            {
                alert("Email Sent");
            }
        })*@

        window.location.href="mailto:"+email+"?Subject=@ViewBag.WW.Replace("'"," ") Delinquent in "+data+"&Body="+data;


    }
    function SendAll()
    {
        var sentTo="Email sent to ";
        $.each(Emails,function(){
            if(EmailsSent.indexOf(this.email)==-1)
            {
                EmailsSent[EmailsSent.length]=this.email.trim();
                sentTo+='<br>'+ this.email;
                Notify(this.email,this.app);
            }
        });

        alert(sentTo);
    }

</script>

AutoIndicators/Views/Reports/Notifweek.cshtml
@using AutoIndicators.Models
@model List<NotifReport>
@section Scripts
{
    <script>
        module = '@ViewBag.Module';
        view=14;
        skip = '../';
        wwid=@ViewBag.WWID;


    </script>
}
@{
    ViewBag.HiddenFilter = false;
    ViewBag.ShowExtra = true;
    ViewBag.Module = "Reports/Notifweek";
}
<table align="left" style="background-color:#0062a8; width:100%; text-align:center">
    <tr>
        <td style="border:2px solid white; background-color:white"><a style="color:#0062a8 !important;" href="/Reports/Notifweek/?year=0">Notification this week</a></td>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("NotifWeek", "Reports", new { year = DateTime.Now.Year, byYear=true })">Notification Annual</a></td>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Delinquent", "Reports")">Delinquent this week by program</a></td>
        <td style="border:2px solid white;"><a style="color:white !important;" href="@Url.Action("Delinquent", "Reports", new { owner = true })">Delinquent this week by owner</a></td>
     
    </tr>
</table>
<br />
<br />
<div style="width:100%; text-align: center"><h3>Notification this week</div>
<br /><br />
@if(ViewBag.ByYear)
{
    int intYear = 0;
    @:Year: <select id="Year">
    foreach (Calendar cal in AutoIndicators.GeneralClasses.ViewDataFilter.Calendar())
    {
        if (cal.Year != intYear)
        {
            if(cal.Year==(int)ViewBag.Year)
            {
                @:<option value="@cal.Year" selected="selected"> @cal.Year</option>
            }else
            {
                @:<option value="@cal.Year"> @cal.Year</option>
            }
            intYear = cal.Year;
        }
    }
    @:</select>
<button onclick="SelYear()">Search</button>
}
<table id="ReporData" style="display:none">
    <tr>
        <th>Notif</th>
        <th>Program</th>
        <th>Owner</th>
        <th>App</th>
        <th>Date</th>
        @if (ViewBag.ByYear)
        {
            <th>WW</th>    
            <th>Incidence %</th>
        }
    </tr>
    @foreach(NotifReport rpt in Model)
    {
        decimal perc = (Model.Where(x => x.AppId == rpt.AppId && x.Program == rpt.Program).Count() * 100) / Model.Where(x => x.AppId == rpt.AppId && x.Program == rpt.Program).FirstOrDefault().Total;
        <tr>
            <td>@rpt.Notif</td>
            <td>@rpt.Program</td>
            <td>@rpt.Owner</td>
            <td>@rpt.AppName</td>
            <td>@rpt.CreateDate</td>
            @if(ViewBag.ByYear)
            {
                <td>@rpt.WWID</td>
                <td>@Math.Ceiling(perc)</td>
            }
        </tr>
    }
</table>
<div>
    <div style="width:30%; float:left; height:30px;"></div>
    <div id="dgReport" style="float:left"></div>
</div>
<script>
    changeToGridReport();
    function changeToGridReport() {
        var tbl = $('#ReporData');
        var type = $('#ReporData').data("type");
        var obj = $.paramquery.tableToArray(tbl);

        var newObj = {
            width: 1024,
            height: 600,
            hwrap: false,
            wrap: false,
            title: "Results",
            //DataGrid Menu
            editable: false,
            collapsible: true,
            rowBorders: true,
            filterModel: { mode: 'AND', header: true, on: true },
            datatype: 'local',
            selectionModel: {
                //type: 'cell'
                type: 'cell'
            },
            numberCell: { width: 50, resizable: true },
            hoverMode: 'row',
            scrollModel: { autoFit: false },
            toolbar: {
                items: [{
                    type: 'button', label: 'Send All Emails', listeners: [{
                        click: function () {
                            SendAll();
                        }
                    }]
                }]}
        };

        newObj.dataModel = {
            data: obj.data,
            sorting: "local",
            sortDir: ["up", "down", "up"]
        };
        newObj.colModel = obj.colModel;

        for (i = 0; i < newObj.colModel.length; i++) {
            newObj.colModel[i].width = "150";
        }



        var items = newObj.dataModel.data;
        var result = [];

        for (x = 0; x < newObj.colModel.length; x++) {
            Val = [];
            for (var item, i = 0; item = items[i++];) {
                if (Val.indexOf(item[x]) < 0) {
                    Val[Val.length] = item[x];
                }
            }
            result[result.length] = Val;
        }
        for (i = 0; i < newObj.colModel.length; i++) {
            newObj.colModel[i].filter = {
                type: 'select',
                attr: "multiple",
                cache: null,
                options: result[i],
                condition: 'range',
                listeners: ['change'],
                init: function () {
                    $(this).pqSelect({ checkbox: true, radio: true, width: '100%' });
                }
            };
        }

        newObj.pageModel = { rPP: 1000, type: "local" };

        $grid = $('#dgReport').pqGrid(newObj);


        try {
            if ($('#dgReport').pqGrid() != null)
                $('#dgReport').pqGrid("destroy");

            $grid = $('#dgReport').pqGrid(newObj);

            $($($('#dgReport').children()[0]).children()[1]).click();
            $($($('#dgReport').children()[0]).children()[1]).click();

        } catch (err) { }
    }
    function SelYear()
    {
        window.location.href='/Reports/Notifweek?year='+$('#Year').val()+"&byYear=true";
    }
</script>

AutoIndicators/Views/Reports/ReportsView.cshtml
@{
    ViewBag.Title = "ReportsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Module = "Reports";
    ViewBag.HiddenFilter = false;
}

@section JSLibs{
    <script src="~/Scripts/reports.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
}
@section Styles{
    <link href="~/Content/report.css" rel="stylesheet" />
    <link href="@Url.Content("~/Content/snapshotStyle.css")" rel="stylesheet" type="text/css" />
}
<h2>Reports</h2>

<div style="width:100%">Report <select id="Report" onchange="LoadReport($(this).val())">
    <option value="0">Select one</option>
    <option value="1">Delinquent for Snapshot</option>
    <option value="2">Health Indicator</option>
    <option value="3">Schedule</option>
    <option value="6">Notification this week</option>
</select><button style="display:none" >View</button>
</div>
<br />
<br />
<div id="ReportViewer" style="width:100%"></div>
@section Scripts
{
    <script>
    module = '@ViewBag.Module';
    view=14;
    skip = '../';
    wwid=@ViewBag.WWID;
    </script>

}