AutoIndicators/Controllers/LuceneSnapshotController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoIndicators.Models;

namespace AutoIndicators.Controllers
{
    public class LuceneSnapshotController : Controller
    {
        //
        // GET: /LuceneSnapshot/
        public ActionResult Index(string SearchTerm, string searchField, int? limit) { //SearchTerm is the string to look for, searchfield is the field we look for, and limit is the number of rows shown on the table
            //Create Lucene Directory
            if (!Directory.Exists(LuceneSearch._luceneDir)) Directory.CreateDirectory(LuceneSearch._luceneDir);

            //Lucene Search
            List<SampleData> _searchResults;
            _searchResults = (string.IsNullOrEmpty(searchField)
                            ? LuceneSearch.Search(SearchTerm)
                            : LuceneSearch.Search(SearchTerm, searchField)).ToList();

            if(string.IsNullOrEmpty(SearchTerm) && !_searchResults.Any())
                _searchResults = LuceneSearch.GetAllIndexRecords().ToList();

            var search_field_list = new
                List<SelectedList> {
				                     	new SelectedList {Text = "(All Fields)", Value = ""},
                                        new SelectedList {Text = "Id", Value = "Id"},
				                     	new SelectedList {Text = "ContinuityID", Value = "ContinuityID"},
				                     	new SelectedList {Text = "PXTName", Value = "PXTName"},
				                     	new SelectedList {Text = "ProgName", Value = "ProgName"},
                                        new SelectedList {Text = "ProgType", Value = "ProgType"},
                                        new SelectedList {Text = "ProgTypeLink", Value = "ProgTypeLink"},
                                        new SelectedList {Text = "PLCStatus", Value = "PLCStatus"},
                                        new SelectedList {Text = "OwnerName", Value = "OwnerName"},
                                        new SelectedList {Text = "Updatetxt", Value = "Updatetxt"}
				                     };

            var limitDb = limit == null ? 3 : Convert.ToInt32(limit);
            List<SampleData> allSampleData;
            if (limitDb > 0)
            {
                allSampleData = SampleDataRepository.GetAll().ToList().Take(limitDb).ToList();
                ViewBag.Limit = SampleDataRepository.GetAll().Count - limitDb;
            }
            else allSampleData = SampleDataRepository.GetAll();

            return View(new IndexViewModel
            {
                AllSampleData = allSampleData,
                SearchIndexData = _searchResults,
                SampleData = new SampleData {ContinuityID="A1234",PXTName="TestName",ProgName="TestProgName",ProgDesc="TestProgDesc",ProgType="TestProgType",ProgTypeLink="TestProgTypeLink",PLCStatus="TestPLCStatus",OwnerName="TestOwnerName",Updatetxt="NewTest" },
                SearchFieldList = search_field_list
            });
        }

        public ActionResult Search(string searchTerm, string searchField, string searchDefault)
        {
            return RedirectToAction("Index", new { searchTerm, searchField, searchDefault });
        }

        public ActionResult CreateIndex() //Create the Search Index
        {
            LuceneSearch.AddUpdateLuceneIndex(SampleDataRepository.GetAll());
            TempData["Result"] = "Search index was created successfully!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddToIndex(SampleData sampleData)
        {
            LuceneSearch.AddUpdateLuceneIndex(sampleData);
            TempData["Result"] = "Record was added to search index successfully!";
            return RedirectToAction("Index");
        }

        public ActionResult ClearIndex()
        {
            if (LuceneSearch.ClearLuceneIndex())
                TempData["Result"] = "Search index was cleared successfully!";
            else
                TempData["ResultFail"] = "Index is locked and cannot be cleared, try again later or clear manually!";
            return RedirectToAction("Index");
        }

        public ActionResult ClearIndexRecord(int id)
        {
            LuceneSearch.ClearLuceneIndexRecord(id);
            TempData["Result"] = "Search index record was deleted successfully!";
            return RedirectToAction("Index");
        }

        public ActionResult OptimizeIndex()
        {
            LuceneSearch.Optimize();
            TempData["Result"] = "Search index was optimized successfully!";
            return RedirectToAction("Index");
        }
        
	}
}

AutoIndicators/Views/LuceneSnapshot/Index.cshtml
@using AutoIndicators.Models
@model IndexViewModel
@*@model dynamic*@
@section Styles{
    <link href="@Url.Content("~/Content/snapshotStyle.css")" rel="stylesheet" type="text/css" />
}
<div class="content_left">
    <span style="color: green;">@TempData["Result"]</span>
    <span style="color: red;">@TempData["ResultFail"]</span>
</div>
<div class="clear"></div>
<div class="col_12">
    <fieldset>
        <legend>Database records (@Html.ActionLink("Create Search Index From Database [+]", "CreateIndex"))</legend>
        <table class="table table-bordered table-striped">
            <tr>
                <th>@Html.LabelFor(m => Model.SampleData.Id)</th>
                <th>@Html.LabelFor(m => Model.SampleData.ContinuityID)</th>
                <th>@Html.LabelFor(m => Model.SampleData.PXTName)</th>
                <th>@Html.LabelFor(m => Model.SampleData.ProgName)</th>
                <th>@Html.LabelFor(m => Model.SampleData.ProgDesc)</th>
                <th>@Html.LabelFor(m => Model.SampleData.ProgType)</th>
                <th>@Html.LabelFor(m => Model.SampleData.ProgTypeLink)</th>
                <th>@Html.LabelFor(m => Model.SampleData.PLCStatus)</th>
                <th>@Html.LabelFor(m => Model.SampleData.OwnerName)</th>
                <th width="45%">@Html.LabelFor(m => Model.SampleData.Updatetxt)</th>
            </tr>
            @foreach (var record in Model.AllSampleData)
            {
                <tr>
                    <td>@record.Id</td>
                    <td>@record.ContinuityID</td>
                    <td>@record.PXTName</td>
                    <td>@record.ProgName</td>
                    <td>@record.ProgDesc</td>
                    <td>@record.ProgType</td>
                    <td>@record.ProgTypeLink</td>
                    <td>@record.PLCStatus</td>
                    <td>@record.OwnerName</td>
                    <td>@Html.Raw(record.Updatetxt)</td>
                </tr>
            }
        </table>

        @if (ViewBag.Limit > 0)
        {
            <div class="margin_top10">And <b>@ViewBag.Limit</b> more records... (<a href="\?limit=0">See All</a>)</div>
        }
    </fieldset>
</div>
<div class="col_12">
    <fieldset>
        <legend>Search (custom, useful for most basic scenarios)</legend>
        <div class="content_left margin_top5">
            <p>Try these searches: <em>"1 3 5", "City", "Russia India", "bel mos ind"</em></p>
        </div>
        @using (Html.BeginForm("Search", "LuceneSnapshot"))
        {
            <div class="content_left margin_top13 margin_left30">
                @Html.CheckBoxFor(m => m.SearchDefault)
                @Html.LabelFor(m => m.SearchDefault, "Use default Lucene query")
            </div>
            <div class="content_left margin_right20">
                @Html.TextBoxFor(m => m.SearchTerm, new { @class = "big", style = "width:650px;", autocomplete = "off" })
            </div>
            <div class="content_left margin_top15 margin_right30">
                @Html.DropDownListFor(m => m.SearchField, Model.SearchFieldList.Select(x => new SelectListItem { Text = x.Text, Value = x.Value }),
          new { style = "width:150px;" })
            </div>
            <div class="content_right margin_top8">
                <input type="submit" value="Search" />
            </div>
            <div class="clear"></div>
        }
    </fieldset>
</div>
<div class="col_8">
    <fieldset>
        <legend>
            Search index
            @*(@Html.ActionLink("Optimize", "OptimizeIndex"))*@
            (@Html.ActionLink("Clear [X]", "ClearIndex"))
        </legend>

        @if (Model.SearchIndexData.Any())
{
    <table class="table table-bordered table-striped">
        <tr>
            <th>@Html.LabelFor(m => Model.SampleData.Id)</th>
            <th>@Html.LabelFor(m => Model.SampleData.ContinuityID)</th>
            <th>@Html.LabelFor(m => Model.SampleData.PXTName)</th>
            <th>@Html.LabelFor(m => Model.SampleData.ProgName)</th>
            <th>@Html.LabelFor(m => Model.SampleData.ProgDesc)</th>
            <th>@Html.LabelFor(m => Model.SampleData.ProgType)</th>
            <th>@Html.LabelFor(m => Model.SampleData.ProgTypeLink)</th>
            <th>@Html.LabelFor(m => Model.SampleData.PLCStatus)</th>
            <th>@Html.LabelFor(m => Model.SampleData.OwnerName)</th>
            <th width="45%">@Html.LabelFor(m => Model.SampleData.Updatetxt)</th>
        </tr>
        @foreach (var record in Model.SearchIndexData)
        {
            <tr>
                <td>@record.Id</td>
                <td>@record.ContinuityID</td>
                <td>@record.PXTName</td>
                <td>@record.ProgName</td>
                <td>@record.ProgDesc</td>
                <td>@record.ProgType</td>
                <td>@record.ProgTypeLink</td>
                <td>@record.PLCStatus</td>
                <td>@record.OwnerName</td>
                <td>@Html.Raw(record.Updatetxt)</td>
            </tr>
        }
    </table>
}
else
{
            <text><br />No search index records found...<br /></text>
        }
    </fieldset>
</div>
<div class="col_4">
    <fieldset class="add_record">
        <legend>Add/Update search index record</legend>
        Use Id of existing one to update
        @using (Html.BeginForm("AddToIndex", "LuceneSnapshot"))
        {
            <div class="form_horizontal">
                <p>
                    @Html.LabelFor(m => m.SampleData.Id)<br />
                    @Html.TextBoxFor(m => m.SampleData.Id, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.ContinuityID)<br />
                    @Html.TextBoxFor(m => m.SampleData.ContinuityID, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.PXTName)<br />
                    @Html.TextBoxFor(m => m.SampleData.PXTName, new { style = "width:15%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.ProgName)<br />
                    @Html.TextBoxFor(m => m.SampleData.ProgName, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.ProgDesc)<br />
                    @Html.TextBoxFor(m => m.SampleData.ProgDesc, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.ProgType)<br />
                    @Html.TextBoxFor(m => m.SampleData.ProgType, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.ProgTypeLink)<br />
                    @Html.TextBoxFor(m => m.SampleData.ProgTypeLink, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.PLCStatus)<br />
                    @Html.TextBoxFor(m => m.SampleData.PLCStatus, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.OwnerName)<br />
                    @Html.TextBoxFor(m => m.SampleData.OwnerName, new { style = "width:10%;" })
                </p>
                <p>
                    @Html.LabelFor(m => m.SampleData.Updatetxt)<br />
                    @Html.TextBoxFor(m => m.SampleData.Updatetxt, new { style = "width:15%;" })
                </p>
            </div>
            <div class="clear"></div>
            <input type="submit" value="Add/Update Record" />
        }
    </fieldset>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#SearchTerm').focus();
        $('.grid tr:even').css("background", "silver");
    });
</script>